version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: internlinkng-postgres
    environment:
      POSTGRES_DB: internlinkng
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Android_Studio1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internlinkng-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ktor Backend
  backend:
    build:
      context: ./internlinkng-backend
      dockerfile: Dockerfile
    container_name: internlinkng-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/internlinkng
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Android_Studio1
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internlinkng-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  internlinkng-network:
    driver: bridge 