services:
  - type: web
    name: internlinkng-backend
    env: docker
    plan: free
    dockerfilePath: ./internlinkng-backend/Dockerfile
    dockerContext: ./internlinkng-backend
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: JWT_SECRET
        generateValue: true
